# -*- coding: utf-8 -*-
import uuid
from main_pack.base.dataMethods import configureNulls, configureFloat

def add_Inv_dict(req):
	return configureNulls({
		#"InvId": req.get('InvId'),
		"InvGuid": req.get('InvGuid'),
		"InvTypeId": req.get('InvTypeId'),
		"InvStatId": req.get('InvStatId'),
		"CurrencyId": req.get('CurrencyId'),
		"RpAccId": req.get('RpAccId'),
		"CId": req.get('CId'),
		"DivId": req.get('DivId'),
		"WhId": req.get('WhId'),
		"WpId": req.get('WpId'),
		"EmpId": req.get('EmpId'),
		"PtId": req.get('PtId'),
		"PmId": req.get('PmId'),
		"InvLatitude": req.get('InvLatitude'),
		"InvLongitude": req.get('InvLongitude'),
		"InvRegNo": req.get('InvRegNo'),
		"InvDesc": req.get('InvDesc'),
		"InvDate": req.get('InvDate'),
		"InvTotal": req.get('InvTotal'),
		"InvExpenseAmount": req.get('InvExpenseAmount'),
		"InvTaxAmount": req.get('InvTaxAmount'),
		"InvDiscountAmount": req.get('InvDiscountAmount'),
		"InvFTotal": req.get('InvFTotal'),
		"InvFTotalInWrite": req.get('InvFTotalInWrite'),
		"InvModifyCount": req.get('InvModifyCount'),
		"InvPrintCount": req.get('InvPrintCount'),
		"InvCreditDays": req.get('InvCreditDays'),
		"InvCreditDesc": req.get('InvCreditDesc'),
		"AddInf1": req.get('AddInf1'),
		"AddInf2": req.get('AddInf2'),
		"AddInf3": req.get('AddInf3'),
		"AddInf4": req.get('AddInf4'),
		"AddInf5": req.get('AddInf5'),
		"AddInf6": req.get('AddInf6'),
		"CreatedDate": req.get('CreatedDate'),
		"ModifiedDate": req.get('ModifiedDate'),
		"SyncDateTime": req.get('SyncDateTime'),
		"CreatedUId": req.get('CreatedUId'),
		"ModifiedUId": req.get('ModifiedUId'),
		"GCRecord": req.get('GCRecord'),	
	})