from main_pack.config import Config

def get_payment_validation_info():
	data = {}
	if Config.ALLOW_PAYMENT_INFO_API:
		data = {
			"HALKBANK_PAYMENT_SERVICE_URL": Config.HALKBANK_PAYMENT_SERVICE_URL,
			"HALKBANK_PAYMENT_SERVICE_USERNAME": Config.HALKBANK_PAYMENT_SERVICE_USERNAME,
			"HALKBANK_PAYMENT_SERVICE_PASSWORD": Config.HALKBANK_PAYMENT_SERVICE_PASSWORD,
		}
	return data